-- Spoof ATD batch load: inserts ATXR + ATDT rows directly from ATDT_BATCH_LOG.
-- Run AFTER pre-adt, INSTEAD of the batch. Then run post-adt to test.
-- WARNING: Creates real records in Facets. Clean up after testing.

DECLARE @CLCL_ID    VARCHAR(50),
        @ATDT_DATA  VARCHAR(255),
        @ATSY_ID    VARCHAR(10),
        @ATLD_ID    VARCHAR(10),
        @ATXR_SRC   DATETIME,
        @ATXR_DEST  DATETIME,
        @Timestamp  VARCHAR(30)

-- Ensure sequence row exists for this connection's SPID.
IF NOT EXISTS (SELECT 1 FROM Facets..CER_SEQS_SEQUENCE WHERE SEQS_SPID = @@SPID % 2000)
BEGIN
    INSERT INTO Facets..CER_SEQS_SEQUENCE (SEQS_SPID, SEQS_CURRENT_DTM)
    VALUES (@@SPID % 2000, GETDATE())
END

DECLARE cur CURSOR LOCAL FAST_FORWARD FOR
    SELECT BLOG.CLCL_ID, BLOG.ATDT_DATA, BLOG.ATSY_ID, BLOG.ATLD_ID, CLCL.ATXR_SOURCE_ID
    FROM FacetsEXT..ATDT_BATCH_LOG BLOG
    JOIN Facets..CMC_CLCL_CLAIM CLCL ON CLCL.CLCL_ID = BLOG.CLCL_ID
    WHERE BLOG.StatusMessage = 'Validated'
      AND CLCL.ATXR_SOURCE_ID IS NOT NULL
      AND CLCL.ATXR_SOURCE_ID <> '1753-01-01T00:00:00'

OPEN cur
FETCH NEXT FROM cur INTO @CLCL_ID, @ATDT_DATA, @ATSY_ID, @ATLD_ID, @ATXR_SRC

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @Timestamp = CONVERT(VARCHAR(30), GETDATE(), 126)

    -- Generate ATXR_DEST_ID from sequence table.
    UPDATE Facets..CER_SEQS_SEQUENCE
    SET SEQS_CURRENT_DTM = SEQS_CURRENT_DTM
    WHERE SEQS_SPID = @@SPID % 2000

    SELECT @ATXR_DEST = DATEADD(MILLISECOND, 10, SEQS_CURRENT_DTM)
    FROM Facets..CER_SEQS_SEQUENCE
    WHERE SEQS_SPID = @@SPID % 2000

    UPDATE Facets..CER_SEQS_SEQUENCE
    SET SEQS_CURRENT_DTM = @ATXR_DEST
    WHERE SEQS_SPID = @@SPID % 2000

    -- Insert ATXR cross-reference
    INSERT INTO Facets..CER_ATXR_ATTACH_U (
        ATXR_SOURCE_ID, ATXR_DEST_ID, ATSY_ID, ATTB_ID, ATTB_TYPE,
        ATXR_DESC, ATXR_CREATE_DT, ATXR_CREATE_USUS,
        ATXR_LAST_UPD_DT, ATXR_LAST_UPD_USUS, ATXR_COMPILED_KEY, ATXR_LOCK_TOKEN
    )
    VALUES (
        @ATXR_SRC, @ATXR_DEST, @ATSY_ID, 'CLCL', 'S',
        'Claim Attachment - Batch', @Timestamp, 'BATCH_SVC',
        @Timestamp, 'BATCH_SVC', '', 1
    )

    -- Insert ATDT data record
    INSERT INTO Facets..CER_ATDT_DATA_D (
        ATSY_ID, ATXR_DEST_ID, ATDT_SEQ_NO, ATDT_DATA, ATLD_ID, ATXR_SOURCE_ID
    )
    VALUES (
        @ATSY_ID, @ATXR_DEST, 0, @ATDT_DATA, @ATLD_ID, @ATXR_SRC
    )

    PRINT 'LOADED ' + @CLCL_ID + ' / ' + @ATDT_DATA

    FETCH NEXT FROM cur INTO @CLCL_ID, @ATDT_DATA, @ATSY_ID, @ATLD_ID, @ATXR_SRC
END

CLOSE cur
DEALLOCATE cur

-- Verify
SELECT
      BLOG.CLCL_ID
    , BLOG.ATDT_DATA
    , ATXR.ATXR_DEST_ID
    , ATXR.ATXR_SOURCE_ID
FROM FacetsEXT..ATDT_BATCH_LOG BLOG
JOIN Facets..CMC_CLCL_CLAIM CLCL ON CLCL.CLCL_ID = BLOG.CLCL_ID
JOIN Facets..CER_ATXR_ATTACH_U ATXR ON ATXR.ATXR_SOURCE_ID = CLCL.ATXR_SOURCE_ID
JOIN Facets..CER_ATDT_DATA_D ATDT
    ON ATDT.ATXR_DEST_ID = ATXR.ATXR_DEST_ID
    AND ATDT.ATDT_DATA   = BLOG.ATDT_DATA
WHERE BLOG.StatusMessage = 'Validated'
